### ISSUE TITLE
Has anyone used it?

### ISSUE THREAD

**Issue by 452283662** [lucbloom/unity_anr_supervisor#1]
How well does it work? 🥳

**Comment by lucbloom** [comment]
It works, technically. We did see a tiny decrease in ANRs in our live build, but in the end my colleagues found the payoff too small to risk force-closing the game. A few weeks back we switched to another ad provider and now enjoy an increase in revenue and a decrease in ANRs.

Anyway, I've updated the repo to include that changes that make it more prudent:
- Only close the application if the thread includes GMS (AdMob) and the status is BLOCKED.
- Only send the first 3 lines of the stack trace. Saves bandwidth and ensures the report gets sent.
