### ISSUE TITLE
Adding Firebase Analytics to log event

### ISSUE THREAD

**Issue by minhaj-inspiredsquare** [lucbloom/unity_anr_supervisor#2]
Hi, I'm trying to add Firebase Analytics to log events but it gave me an error and did not compile the apk.
Here is the code I'm trying to add:

`import com.google.firebase.analytics.FirebaseAnalytics;`

Right after the event is logged on Crashlytics I added this:

```
Bundle params = new Bundle();
params.putString("ANR Crash", "ANR Crash");
FirebaseAnalytics.getInstance().logEvent("ANR_crash", params);
```
And here is the error:

```
/Users/abc/Work/workProject/working/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/ANRSupervisor.java:55: error: method getInstance in class FirebaseAnalytics cannot be applied to given types;
        FirebaseAnalytics.getInstance().logEvent("ANR_crash", params);
                ^
  required: Context
  found: no arguments
  reason: actual and formal argument lists differ in length
Note: /Users/abc/Work/workProject/working/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/unity3d/player/UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unityLibrary:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

```

Any help will be highly appreciated. Thanks

**Comment by lucbloom** [comment]
Seems like you're not passing the required argument "context".
 ```
 required: Context
  found: no arguments
```

First hit in Google confirmed:
https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics
`Applications can get an instance of this class by calling [getInstance(Context)](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#getInstance(android.content.Context)). [getInstance(Context)](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#getInstance(android.content.Context)) is thread safe and can be called from any thread.`
