### ISSUE TITLE
Azure Cosmos implementation into Unity has some issues

### ISSUE THREAD

**Issue by xuwoan** [lucbloom/unity_anr_supervisor#3]
When I download Azure.Cosmos from Nuget package manager and add the dll file to Unity. It results me with message imply that i can't use these DLL files (Missing packages)

I'm not sure this is the right method to implement. If not please send me a detailed tutorial to solve this problem, document attached would be great. Appreciate for your help!

**Comment by lucbloom** [comment]
I don't know if I didn't configure it correctly, but I found Cosmos to be cumbersome and slow. I myself moved away from it towards Google Firestore.
- What's up with the partition key? It's kinda vague and counter intuitive.
- Cosmos DB interface is just... abysmal. With the constant refreshing etc.
- Somehow, a 100 document table was already noticeable slow. Again, could be me.
I think a multi-billion company like MS can make some tight stuff, but it wasn't for me.

In turn, I won't be able to help you very much.
